name: 🐛 Bug Report
description: Create a report to help us improve stencil-sass-alias
title: 'bug: '

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/cheese-grinder/stencil-sass-alias/blob/main/CONTRIBUTING.md#creating-an-issue).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/cheese-grinder/stencil-sass-alias/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I have searched for [existing issues](https://github.com/cheese-grinder/stencil-sass-alias/issues) that already report this problem, without success.
          required: true

  - type: dropdown
    id: affected-versions
    attributes:
      label: Version
      description: Which version(s) of stencil-sass-alias does this issue impact?
      options:
        - v0.x
      multiple: true
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Code Reproduction URL
      description: Please reproduce this issue in a blank Poppy UI starter application and provide a link to the repo.
      placeholder: https://github.com/...

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.